#!/usr/bin/env python3

import sys
import datetime

# for arg in sys.argv:
#   if arg == 'in':
#     # open('punch_card.json', 'w')
#     date = datetime.datetime.now().date()
#     time = str(datetime.datetime.now().time())[:8]
def parse_args():
  args = {
    u'commands': {
      u'in': {
        u'command': ['in'],
        u'help': ['in', 'Punch in at current date/time']
      },
      u'out': {
        u'command': ['out'],
        u'help': ['out', 'Punch out at current date/time']
      }
    },
    u'flags': {
      u'help': {
        u'flag': ['-h', '--help'],
      }
    }
  }

  def recursion(d):
    for k, v in d.items():
      if isinstance(v, dict):
        recursion(v)
      else:
        print('{0} : {1}'.format(k, v))

  recursion(args)


def main():
  parse_args()

main()
