#!/usr/bin/env python3

import json
import os.path
import sys
import getpass
import datetime

# for arg in sys.argv:
#   if arg == 'in':
#     # open('punch_card.json', 'w')
#     date = datetime.datetime.now().date()
#     time = str(datetime.datetime.now().time())[:8]
def parse_args():
  for arg in sys.argv[1:]:
    if arg == 'in' or arg == 'out':
      punch(arg)

def punch(option):
  user = getpass.getuser()
  date = str(datetime.datetime.now().date())
  time = str(datetime.datetime.now().time())[:8]

  clock = {
    user: {
      date: {
        time: option
      }
    }
  }

  if not os.path.exists('./punchcard.json'):
    write_file('punchcard.json', clock)
  else:
    with open('punchcard.json', 'r') as punchcard:
      punch_card = json.load(punchcard)
      if punch_card[user]:
        if punch_card[user][date]:
          time = {**punch_card[user][date], **clock[user][date]}
          punch_card[user][date] = time

      write_file('punchcard.json', punch_card)

def write_file(_file, update):
  with open(_file, 'w+') as punchcard:
    json.dump(update, punchcard)

def main():
  parse_args()

main()
